name: 'Pull Request'

on:
  pull_request:
    types: [opened]

jobs:
  decorate:
    name: 'Open'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Self-Assign PR
        uses: technote-space/assign-author@v1
