name: 'Transpile'

on: [pull_request]

env:
  CACHE_KEY: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

jobs:
  transpile:
    name: 'Transpile => ${{ matrix.version }}'
    strategy:
      matrix:
        version: [esnext, cjs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: yarn
        with:
          path: '**/node_modules'
          key: ${{ env.CACHE_KEY }}

      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --silent --prefer-offline

      - name: Transpile
        run: |
          NODE_ENV=production yarn transpile:${{ matrix.version }}
          NODE_ENV=development yarn transpile:${{ matrix.version }}
