name: 'Unit Testing'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  jest:
    name: 'Jest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: yarn
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --silent --prefer-offline

      - name: Jest Testing
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
        with:
          coverageCommand: yarn test
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
