name: 'Versioning'

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  versioning:
    name: 'SemVer'
    if: '${{ github.event.pull_request.merged == true }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/cache@v2
        id: yarn
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --silent --prefer-offline

      - name: Executing Semantic Versioning
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

          yarn standard-version
          echo "::set-output name=version::$(cat package.json | jq -r '.version')"
          echo "::set-output name=name::$(cat package.json | jq -r '.name')"

          git push --follow-tags

      - name: Publishing v${{ steps.semver.outputs.version }} to the NPM registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
